add_lunch_combo angler-userdebug
add_lunch_combo bullhead-userdebug
add_lunch_combo taimen-userdebug
add_lunch_combo walleye-userdebug
add_lunch_combo crosshatch-userdebug
add_lunch_combo blueline-userdebug
